import type { Standard } from "@/lib/types";

export const standardsSeed: Standard[] = [
  {
    code: "CCSS.MATH.CONTENT.1.NBT.B.2",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "K-2",
    description: "Understand that the two digits of a two-digit number represent amounts of tens and ones.",
  },
  {
    code: "CCSS.MATH.CONTENT.2.OA.C.3",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "K-2",
    description: "Determine whether a group of objects has an odd or even number of members.",
  },
  {
    code: "CCSS.MATH.CONTENT.3.NF.A.1",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Understand a fraction 1/b as the quantity formed by 1 part when a whole is partitioned into b equal parts.",
  },
  {
    code: "CCSS.MATH.CONTENT.3.MD.B.3",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Draw a scaled picture graph and a scaled bar graph to represent a data set with several categories.",
  },
  {
    code: "CCSS.MATH.CONTENT.3.OA.D.8",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Solve two-step word problems using the four operations.",
  },
  {
    code: "CCSS.MATH.CONTENT.4.NF.A.1",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Explain why a fraction a/b is equivalent to a fraction (n × a)/(n × b).",
  },
  {
    code: "CCSS.MATH.CONTENT.4.MD.A.2",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Use the four operations to solve word problems involving distances, intervals of time, and money.",
  },
  {
    code: "CCSS.MATH.CONTENT.4.G.A.3",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Recognize a line of symmetry for a two-dimensional figure.",
  },
  {
    code: "CCSS.MATH.CONTENT.5.NBT.B.7",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Add, subtract, multiply, and divide decimals to hundredths.",
  },
  {
    code: "CCSS.MATH.CONTENT.5.MD.C.5",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "3-5",
    description: "Relate volume to multiplication and addition and solve real world problems.",
  },
  {
    code: "CCSS.MATH.CONTENT.6.RP.A.3",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "6-8",
    description: "Use ratio and rate reasoning to solve real-world and mathematical problems.",
  },
  {
    code: "CCSS.MATH.CONTENT.6.EE.B.7",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "6-8",
    description: "Solve real-world and mathematical problems by writing and solving equations of the form x + p = q and px = q.",
  },
  {
    code: "CCSS.MATH.CONTENT.7.RP.A.2",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "6-8",
    description: "Recognize and represent proportional relationships between quantities.",
  },
  {
    code: "CCSS.MATH.CONTENT.7.G.B.6",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "6-8",
    description: "Solve real-world and mathematical problems involving area, volume, and surface area.",
  },
  {
    code: "CCSS.MATH.CONTENT.8.SP.A.1",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "6-8",
    description: "Construct and interpret scatter plots for bivariate measurement data.",
  },
  {
    code: "CASEL.SELF_AWARENESS",
    framework: "CASEL",
    subject: "SEL",
    gradeBand: "K-2",
    description: "Students identify emotions, interests, and strengths that influence learning decisions.",
  },
  {
    code: "CASEL.SELF_MANAGEMENT",
    framework: "CASEL",
    subject: "SEL",
    gradeBand: "3-5",
    description: "Students manage impulses, set goals, and persist through productive struggle.",
  },
  {
    code: "CASEL.SOCIAL_AWARENESS",
    framework: "CASEL",
    subject: "SEL",
    gradeBand: "6-8",
    description: "Students take the perspective of others and respond with empathy.",
  },
  {
    code: "CASEL.RELATIONSHIP_SKILLS",
    framework: "CASEL",
    subject: "SEL",
    gradeBand: "6-8",
    description: "Students communicate clearly, cooperate, and resolve disagreements constructively.",
  },
  {
    code: "CASEL.RESPONSIBLE_DECISION_MAKING",
    framework: "CASEL",
    subject: "SEL",
    gradeBand: "9-12",
    description: "Students evaluate consequences and make ethical, caring, and safe choices.",
  },
  {
    code: "CCSS.MATH.CONTENT.K.CC.B.4",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "K-2",
    description: "Understand the relationship between numbers and quantities and connect counting to cardinality.",
  },
  {
    code: "CCSS.MATH.CONTENT.K.OA.A.1",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "K-2",
    description: "Represent addition and subtraction with objects, fingers, mental images, drawings, sounds, acting out situations, verbal explanations, expressions, or equations.",
  },
  {
    code: "CCSS.MATH.CONTENT.2.MD.D.10",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "K-2",
    description: "Draw a picture graph and a bar graph with a single-unit scale to represent a data set with up to four categories.",
  },
  {
    code: "CCSS.MATH.CONTENT.8.EE.C.7",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "6-8",
    description: "Solve linear equations in one variable.",
  },
  {
    code: "CCSS.MATH.CONTENT.HSA.CED.A.2",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "9-12",
    description: "Create equations in two or more variables to represent relationships between quantities and graph equations on coordinate axes with labels and scales.",
  },
  {
    code: "CCSS.MATH.CONTENT.HSF.IF.B.4",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "9-12",
    description: "Interpret key features of graphs and tables in terms of the quantities, and sketch graphs showing key features given a verbal description of the relationship.",
  },
  {
    code: "CCSS.MATH.CONTENT.HSF.LE.A.1",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "9-12",
    description: "Distinguish between situations that can be modeled with linear functions and with exponential functions.",
  },
  {
    code: "CCSS.MATH.CONTENT.HSA.REI.D.11",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "9-12",
    description: "Explain why the x-coordinates of the points where the graphs of the equations y = f(x) and y = g(x) intersect are the solutions of the equation f(x) = g(x), and find the solutions approximately.",
  },
  {
    code: "CCSS.MATH.CONTENT.HSS.ID.B.6",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "9-12",
    description: "Represent data on two quantitative variables on a scatter plot, and describe how the variables are related.",
  },
  {
    code: "CCSS.MATH.CONTENT.HSG.MG.A.3",
    framework: "Common Core Math",
    subject: "Math",
    gradeBand: "9-12",
    description: "Apply geometric methods to solve design problems.",
  },
];
